<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="13" hostname="DESKTOP-NQRRDTM" name="tests.Surus" tests="14" failures="0" timestamp="24 Tem 2020 16:26:55 GMT" time="439.713" errors="1">
  <testcase name="setUp" time="41.306" classname="tests.Surus">
    <error type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &#039;Command &#039;C:\\Users\\emre\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 5210d014508dc3e1 install -r C:\\Users\\emre\\AppData\\Local\\Temp\\2020624-28592-1mddcpm.dwsc\\appium-uiautomator2-server-v4.5.5.apk&#039; exited with code 1&#039;; Stderr: &#039;adb: failed to install C:\Users\emre\AppData\Local\Temp\2020624-28592-1mddcpm.dwsc\appium-uiautomator2-server-v4.5.5.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl33508770.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]&#039;; Code: &#039;1&#039;
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-NQRRDTM&#039;, ip: &#039;192.168.8.120&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_241&#039;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &#039;Command &#039;C:\\Users\\emre\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 5210d014508dc3e1 install -r C:\\Users\\emre\\AppData\\Local\\Temp\\2020624-28592-1mddcpm.dwsc\\appium-uiautomator2-server-v4.5.5.apk&#039; exited with code 1&#039;; Stderr: &#039;adb: failed to install C:\Users\emre\AppData\Local\Temp\2020624-28592-1mddcpm.dwsc\appium-uiautomator2-server-v4.5.5.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl33508770.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]&#039;; Code: &#039;1&#039;
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-NQRRDTM&#039;, ip: &#039;192.168.8.120&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_241&#039;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\emre\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 5210d014508dc3e1 install -r C:\\Users\\emre\\AppData\\Local\\Temp\\2020624-28592-1mddcpm.dwsc\\appium-uiautomator2-server-v4.5.5.apk' exited with code 1'; Stderr: 'adb: failed to install C:\Users\emre\AppData\Local\Temp\2020624-28592-1mddcpm.dwsc\appium-uiautomator2-server-v4.5.5.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl33508770.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-NQRRDTM', ip: '192.168.8.120', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\emre\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 5210d014508dc3e1 install -r C:\\Users\\emre\\AppData\\Local\\Temp\\2020624-28592-1mddcpm.dwsc\\appium-uiautomator2-server-v4.5.5.apk' exited with code 1'; Stderr: 'adb: failed to install C:\Users\emre\AppData\Local\Temp\2020624-28592-1mddcpm.dwsc\appium-uiautomator2-server-v4.5.5.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl33508770.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]'; Code: '1'
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-NQRRDTM', ip: '192.168.8.120', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at utilities.TestBase.setUp(TestBase.java:76)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 29 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\emre\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 5210d014508dc3e1 install -r C:\\Users\\emre\\AppData\\Local\\Temp\\2020624-28592-1mddcpm.dwsc\\appium-uiautomator2-server-v4.5.5.apk' exited with code 1'; Stderr: 'adb: failed to install C:\Users\emre\AppData\Local\Temp\2020624-28592-1mddcpm.dwsc\appium-uiautomator2-server-v4.5.5.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl33508770.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-NQRRDTM', ip: '192.168.8.120', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\emre\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 5210d014508dc3e1 install -r C:\\Users\\emre\\AppData\\Local\\Temp\\2020624-28592-1mddcpm.dwsc\\appium-uiautomator2-server-v4.5.5.apk' exited with code 1'; Stderr: 'adb: failed to install C:\Users\emre\AppData\Local\Temp\2020624-28592-1mddcpm.dwsc\appium-uiautomator2-server-v4.5.5.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl33508770.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]'; Code: '1'
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
... 33 more
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="TC_034_Surus_Basladi_Kodlu_Kilit" time="36.160" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_034_Surus_Basladi_Kodlu_Kilit -->
  <testcase name="TC_035_Surus_Baslat" time="35.899" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_035_Surus_Baslat -->
  <testcase name="TC_036_Nasil_Surulur_Gecilmemis" time="36.317" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_036_Nasil_Surulur_Gecilmemis -->
  <testcase name="TC_037_Acil_Mudahale" time="36.846" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_037_Acil_Mudahale -->
  <testcase name="TC_038_Nasil_Surulur" time="36.779" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_038_Nasil_Surulur -->
  <testcase name="TC_039_Ortalama" time="35.983" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_039_Ortalama -->
  <testcase name="TC_040_Surus_Bitirme" time="36.184" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_040_Surus_Bitirme -->
  <testcase name="TC_041_Park_Edilemez_Alan" time="35.335" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_041_Park_Edilemez_Alan -->
  <testcase name="TC_042_Kilit_Takilmadi" time="36.212" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_042_Kilit_Takilmadi -->
  <testcase name="TC_044_Surus_Bitir_Internet_Kapali" time="36.381" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_044_Surus_Bitir_Internet_Kapali -->
  <testcase name="TC_045_Ceza_Kurallarina_Erisim" time="36.098" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_045_Ceza_Kurallarina_Erisim -->
  <testcase name="TC_046_Odeme_Hatasi" time="0.213" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_046_Odeme_Hatasi -->
  <testcase name="TC_047_Surus_Bitirme_Basarili" time="0.000" classname="tests.Surus">
    <skipped/>
  </testcase> <!-- TC_047_Surus_Bitirme_Basarili -->
</testsuite> <!-- tests.Surus -->
