<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-NQRRDTM" ignored="0" name="API Tests" tests="1" failures="1" timestamp="15 Eyl 2020 14:25:18 GMT" time="5.96" errors="0">
  <testcase name="TC_028_swapper_batteryDetail" time="4.318" classname="tests.ride.api.Marti_Operator_App_API">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [BATTERY_NOT_FOUND]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [BATTERY_NOT_FOUND]
at utilities.TestBase.run_ws(TestBase.java:310)
at tests.ride.api.Marti_Operator_App_API.TC_028_swapper_batteryDetail(Marti_Operator_App_API.java:652)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TC_028_swapper_batteryDetail -->
</testsuite> <!-- API Tests -->
